In [1]:
#import warnings
from chefboost import Chefboost as chef
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import accuracy_score,f1_score
from sklearn.metrics import f1_score,confusion_matrix,roc_auc_score
from sklearn.model_selection import train_test_split,StratifiedKFold

In [2]:
all_merged=pd.read_csv("C:/Users/Melaku/Desktop/Thesis_02/csv/final02.csv",sep=',',index_col='hhid')

In [3]:
all_merged.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'main_occupation', 'marital_status',
       'Q3098n', 'Q3099n', 'Q30910n', 'Q30911n', 'food_secured'],
      dtype='object')

In [4]:
all_merged.shape

(13626, 25)

In [5]:
all_merged.astype(int)

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,...,Q5233,Q5234,Q524,main_occupation,marital_status,Q3098n,Q3099n,Q30910n,Q30911n,food_secured
hhid,,,,,,,,,,,,,,,,,,,,,
DT0100002,1,1,0,0,1,2,1,1,3,2,...,2,2,1,2,1,1,1,1,1,0
DT0100005,1,1,1,0,1,2,1,1,1,3,...,2,2,1,3,1,0,0,0,0,0
DT0100006,0,1,3,0,1,2,1,1,1,3,...,2,2,1,4,1,0,0,0,0,1
DT0100007,0,1,3,0,1,2,1,1,1,3,...,2,2,1,4,1,0,0,1,0,0
DT0100011,0,1,3,0,0,2,1,1,1,3,...,2,2,1,2,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1301282,1,0,0,1,1,2,2,1,3,2,...,2,2,1,2,4,1,0,1,1,1
DT1301283,1,1,1,1,1,2,2,1,4,2,...,2,2,1,2,1,1,0,1,1,0
DT1301284,1,1,3,1,1,2,2,1,3,2,...,2,2,1,2,1,1,1,1,1,0
DT1301285,1,1,1,1,1,2,2,1,3,2,...,2,2,2,2,1,1,2,1,1,1
DT1301286,1,1,0,1,1,2,2,1,3,2,...,2,2,1,2,1,1,0,1,0,0

In [6]:
all_merged.sort_index()

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,...,Q5233,Q5234,Q524,main_occupation,marital_status,Q3098n,Q3099n,Q30910n,Q30911n,food_secured
hhid,,,,,,,,,,,,,,,,,,,,,
DT0100002,1,1,0,0,1,2,1,1,3,2,...,2,2,1,2,1,1,1,1,1,0
DT0100005,1,1,1,0,1,2,1,1,1,3,...,2,2,1,3,1,0,0,0,0,0
DT0100006,0,1,3,0,1,2,1,1,1,3,...,2,2,1,4,1,0,0,0,0,1
DT0100007,0,1,3,0,1,2,1,1,1,3,...,2,2,1,4,1,0,0,1,0,0
DT0100011,0,1,3,0,0,2,1,1,1,3,...,2,2,1,2,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1301282,1,0,0,1,1,2,2,1,3,2,...,2,2,1,2,4,1,0,1,1,1
DT1301283,1,1,1,1,1,2,2,1,4,2,...,2,2,1,2,1,1,0,1,1,0
DT1301284,1,1,3,1,1,2,2,1,3,2,...,2,2,1,2,1,1,1,1,1,0
DT1301285,1,1,1,1,1,2,2,1,3,2,...,2,2,2,2,1,1,2,1,1,1
DT1301286,1,1,0,1,1,2,2,1,3,2,...,2,2,1,2,1,1,0,1,0,0

In [7]:
#all_merged.rename(columns={"food_secured":"Decision"},inplace=True)

In [8]:
print(type(all_merged))

<class 'pandas.core.frame.DataFrame'>

In [9]:
all_merged.shape

(13626, 25)

In [10]:
all_merged.isnull().sum().sum()

0

In [11]:
all_merged.shape

(13626, 25)

In [12]:
all_merged.duplicated().sum()

1471

In [13]:
#all_merged.drop_duplicates(inplace=True)

In [14]:
all_merged['hh_members'].value_counts(0)

0    7505
1    5744
2     377
Name: hh_members, dtype: int64

In [15]:
all_merged.shape

(13626, 25)

In [16]:
all_merged.rename(columns={"food_secured": "Food_secured"},inplace=True)

In [17]:
#all_merged['target'].replace({2:0},inplace=True)
all_merged['Food_secured'].replace({0:"No",1:"Yes"},inplace=True)

In [18]:
#all_merged['hh_members'].replace({0:"1-4",1:"5-8",2:">=9"},inplace=True)
all_merged['hh_members'].replace({0:"1-4",1:"5-8",2:">=9"},inplace=True)

In [19]:
all_merged['sex'].replace({0:"Female",1:"Male"},inplace=True)

In [20]:
all_merged['hh_education'].value_counts()

0    7017
1    3218
2    1541
3    1252
4     598
Name: hh_education, dtype: int64

In [21]:
all_merged['hh_education'].replace({0:"Illitrate",1:'Elementary',2:"Secondary",3:"Teritary",4:"Teritary"},inplace=True)

In [22]:
all_merged['main_occupation'].value_counts()

2    10689
4     1225
3     1143
1      395
0      174
Name: main_occupation, dtype: int64

In [23]:
all_merged['main_occupation'].replace({0:"Other",1:"Student",2:"Farmer",3:"Self_employmnet",4:"Employee"},inplace=True)

In [24]:
all_merged['marital_status'].value_counts()

1    9338
4    1799
3    1315
2     689
0     485
Name: marital_status, dtype: int64

In [25]:
all_merged['marital_status'].replace({0:"Separated",1:"Married",2:"Single",3:"Divorced",4:"Widowed"},inplace=True)

In [26]:
all_merged['age'].value_counts()

1    6268
0    5076
2    2282
Name: age, dtype: int64

In [27]:
all_merged['age'].replace({0:"15-38",1:"39-60",2:"61-84"},inplace=True)

In [28]:
all_merged['altitude'].value_counts()

2    10114
1     2082
0     1430
Name: altitude, dtype: int64

In [29]:
all_merged['altitude'].replace({0:"Kolla",1:"Woina_dega",2:"Dega"},inplace=True)

In [30]:
all_merged['Q401'].value_counts()

2    6995
1    6631
Name: Q401, dtype: int64

In [31]:
all_merged['Q401'].replace({1:"Clean",2:"Unclean"},inplace=True)

In [32]:
all_merged['Q3098n'].value_counts()

1    8092
0    5534
Name: Q3098n, dtype: int64

In [33]:
all_merged['Q3098n'].replace({0:"none",1:"1-3"},inplace=True)

In [34]:
all_merged['Q30910n'].value_counts()

0    9084
1    4542
Name: Q30910n, dtype: int64

In [35]:
all_merged['Q30910n'].replace({0:"None",1:"1-5"},inplace=True)

In [36]:
all_merged['Q30911n'].value_counts()

1    7351
0    6275
Name: Q30911n, dtype: int64

In [37]:
all_merged['Q30911n'].replace({0:"none",1:"1-3"},inplace=True)

In [38]:
all_merged['Q306'].value_counts()

3    7894
1    4283
4    1364
2      85
Name: Q306, dtype: int64

In [39]:
all_merged['Q306'].replace({1:"Electricity",2:"Kerosene",3:"Battry",4:"Wood/other"},inplace=True)

In [40]:
all_merged['Q307'].value_counts()

2    9146
3    3298
1    1021
4     161
Name: Q307, dtype: int64

In [41]:
all_merged['Q307'].replace({1:"Wood",2:"Muck",3:"Charcoal",4:"Electricity"},inplace=True)

In [42]:
all_merged['Q308m'].value_counts()

0    10432
1     3194
Name: Q308m, dtype: int64

In [43]:
all_merged['Q308m'].replace({0:"No",1:"Yes"},inplace=True)

In [44]:
all_merged['Qsou_inform'].value_counts()

0    8872
1    2991
2    1405
3     358
Name: Qsou_inform, dtype: int64

In [46]:
all_merged['Qsou_inform'].replace({0:"Never",1:"One_media",2:"Two_media",3:"Three_media"},inplace=True)

In [47]:
all_merged['Q504'].value_counts()

2    6415
1    5292
4     856
5     743
3     320
Name: Q504, dtype: int64

In [49]:
all_merged['Q504'].replace({1:"Own_production",2:"Purchase",3:"Support",4:"Land_Rent",5:"Other"},inplace=True)

In [50]:
all_merged['Q524'].replace({2:"No",1:"Yes"},inplace=True)

In [51]:
all_merged['Q5231'].replace({1:"Yes",2:"No"},inplace=True)

In [52]:
all_merged['Q5232'].replace({1:"Yes",2:"No"},inplace=True)

In [53]:
all_merged['Q5233'].replace({1:"Yes",2:"No"},inplace=True)

In [54]:
all_merged['Q5234'].replace({1:"Yes",2:"No"},inplace=True)

In [55]:
all_merged['residence'].replace({1:"Rural",0:"Urban"},inplace=True)

In [56]:
all_merged['Q304'].value_counts()

1    11225
2     1849
3      552
Name: Q304, dtype: int64

In [57]:
all_merged['Q304'].replace({1:"Rent",2:"Private",3:"Government"},inplace=True)

In [58]:
all_merged.dtypes

hh_members         object
sex                object
hh_education       object
residence          object
age                object
altitude           object
Q401               object
Q304               object
Q306               object
Q307               object
Q308m              object
Qsou_inform        object
Q504               object
Q5231              object
Q5232              object
Q5233              object
Q5234              object
Q524               object
main_occupation    object
marital_status     object
Q3098n             object
Q3099n              int64
Q30910n            object
Q30911n            object
Food_secured       object
dtype: object

In [59]:
all_merged

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,...,Q5233,Q5234,Q524,main_occupation,marital_status,Q3098n,Q3099n,Q30910n,Q30911n,Food_secured
hhid,,,,,,,,,,,,,,,,,,,,,
DT0100002,5-8,Male,Illitrate,Urban,39-60,Dega,Clean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,1,1-5,1-3,No
DT0100005,5-8,Male,Elementary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Self_employmnet,Married,none,0,None,none,No
DT0100006,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Employee,Married,none,0,None,none,Yes
DT0100007,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Employee,Married,none,0,1-5,none,No
DT0100011,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Farmer,Single,none,0,None,none,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1301282,5-8,Female,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Widowed,1-3,0,1-5,1-3,Yes
DT1301283,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Wood/other,Muck,...,No,No,Yes,Farmer,Married,1-3,0,1-5,1-3,No
DT1301284,5-8,Male,Teritary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,1,1-5,1-3,No
DT1301285,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,No,Farmer,Married,1-3,2,1-5,1-3,Yes
DT1301286,5-8,Male,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,0,1-5,none,No

In [60]:
from chefboost import Chefboost as chef

In [61]:
all_merged.shape

(13626, 25)

In [62]:
all_merged

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,...,Q5233,Q5234,Q524,main_occupation,marital_status,Q3098n,Q3099n,Q30910n,Q30911n,Food_secured
hhid,,,,,,,,,,,,,,,,,,,,,
DT0100002,5-8,Male,Illitrate,Urban,39-60,Dega,Clean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,1,1-5,1-3,No
DT0100005,5-8,Male,Elementary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Self_employmnet,Married,none,0,None,none,No
DT0100006,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Employee,Married,none,0,None,none,Yes
DT0100007,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Employee,Married,none,0,1-5,none,No
DT0100011,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Rent,Electricity,Charcoal,...,No,No,Yes,Farmer,Single,none,0,None,none,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1301282,5-8,Female,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Widowed,1-3,0,1-5,1-3,Yes
DT1301283,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Wood/other,Muck,...,No,No,Yes,Farmer,Married,1-3,0,1-5,1-3,No
DT1301284,5-8,Male,Teritary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,1,1-5,1-3,No
DT1301285,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,No,Farmer,Married,1-3,2,1-5,1-3,Yes
DT1301286,5-8,Male,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,...,No,No,Yes,Farmer,Married,1-3,0,1-5,none,No

In [63]:
all_merged.rename(columns={'Food_secured':'Decision'},inplace=True)

In [64]:
all_merged.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'main_occupation', 'marital_status',
       'Q3098n', 'Q3099n', 'Q30910n', 'Q30911n', 'Decision'],
      dtype='object')

In [65]:
relevant=['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524','Decision']

In [66]:
all_merged=all_merged[relevant]

In [67]:
all_merged.shape

(13626, 19)

In [68]:
all_merged.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'Decision'],
      dtype='object')

In [69]:
len(all_merged)

13626

In [70]:
all_merged

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,Q308m,Qsou_inform,Q504,Q5231,Q5232,Q5233,Q5234,Q524,Decision
hhid,,,,,,,,,,,,,,,,,,,
DT0100002,5-8,Male,Illitrate,Urban,39-60,Dega,Clean,Rent,Battry,Muck,No,Never,Land_Rent,Yes,No,No,No,Yes,No
DT0100005,5-8,Male,Elementary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,Yes,One_media,Purchase,Yes,No,No,No,Yes,No
DT0100006,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,Yes,Three_media,Purchase,No,No,No,No,Yes,Yes
DT0100007,1-4,Male,Teritary,Urban,39-60,Dega,Clean,Rent,Electricity,Charcoal,Yes,Three_media,Purchase,No,No,No,No,Yes,No
DT0100011,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Rent,Electricity,Charcoal,No,Two_media,Purchase,Yes,No,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1301282,5-8,Female,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes,Yes
DT1301283,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Wood/other,Muck,Yes,One_media,Purchase,No,No,No,No,Yes,No
DT1301284,5-8,Male,Teritary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,Yes,One_media,Own_production,Yes,No,No,No,Yes,No
DT1301285,5-8,Male,Elementary,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,No,One_media,Own_production,No,No,No,No,No,Yes
DT1301286,5-8,Male,Illitrate,Rural,39-60,Dega,Unclean,Rent,Battry,Muck,No,Never,Purchase,No,Yes,No,No,Yes,No

In [71]:
all_merged.shape

(13626, 19)

In [72]:
#Here again we identify both independet and depedent variables in to x and y
x=all_merged.drop(['Decision'],axis=1)
y=all_merged['Decision']

In [73]:
#Split the dataset into train and test set 
x_train,x_test,y_train,y_test =train_test_split(x,y, test_size=0.2,random_state=0)

In [74]:
print(x_train.shape,x_test.shape)#show shape of X_train and Y_train

(10900, 18) (2726, 18)

In [75]:
print(y_train.shape,y_test.shape)

(10900,) (2726,)

In [76]:
all_merged.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'Decision'],
      dtype='object')

In [77]:
all_merged.shape

(13626, 19)

In [79]:
train=x_train[['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524']]

In [80]:
len(train)

10900

In [81]:
test=x_test[['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524']]

In [82]:
train

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,Q308m,Qsou_inform,Q504,Q5231,Q5232,Q5233,Q5234,Q524
hhid,,,,,,,,,,,,,,,,,,
DT0101175,1-4,Male,Elementary,Urban,61-84,Dega,Clean,Rent,Electricity,Charcoal,Yes,One_media,Purchase,Yes,No,No,No,No
DT0800529,>=9,Male,Elementary,Rural,39-60,Woina_dega,Unclean,Rent,Battry,Muck,No,One_media,Own_production,No,No,No,No,Yes
DT0801695,1-4,Male,Illitrate,Rural,15-38,Kolla,Unclean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes
DT0101087,1-4,Female,Illitrate,Urban,61-84,Dega,Clean,Rent,Electricity,Charcoal,Yes,Two_media,Purchase,No,No,No,No,No
DT0800565,1-4,Male,Secondary,Rural,15-38,Kolla,Unclean,Rent,Battry,Muck,No,One_media,Own_production,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1300742,1-4,Female,Illitrate,Rural,39-60,Dega,Clean,Rent,Battry,Muck,Yes,Never,Purchase,No,Yes,No,No,Yes
DT0301118,1-4,Male,Illitrate,Rural,15-38,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,Yes,No,No,No,Yes
DT1100717,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Rent,Battry,Charcoal,Yes,One_media,Purchase,No,No,No,No,Yes
DT1200527,5-8,Male,Illitrate,Rural,61-84,Dega,Unclean,Rent,Wood/other,Muck,No,Never,Purchase,No,No,No,No,No
DT0300270,1-4,Male,Illitrate,Rural,61-84,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes

In [83]:
train=pd.concat([train,y_train],axis=1)
train

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,Q308m,Qsou_inform,Q504,Q5231,Q5232,Q5233,Q5234,Q524,Decision
hhid,,,,,,,,,,,,,,,,,,,
DT0101175,1-4,Male,Elementary,Urban,61-84,Dega,Clean,Rent,Electricity,Charcoal,Yes,One_media,Purchase,Yes,No,No,No,No,No
DT0800529,>=9,Male,Elementary,Rural,39-60,Woina_dega,Unclean,Rent,Battry,Muck,No,One_media,Own_production,No,No,No,No,Yes,Yes
DT0801695,1-4,Male,Illitrate,Rural,15-38,Kolla,Unclean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes,No
DT0101087,1-4,Female,Illitrate,Urban,61-84,Dega,Clean,Rent,Electricity,Charcoal,Yes,Two_media,Purchase,No,No,No,No,No,Yes
DT0800565,1-4,Male,Secondary,Rural,15-38,Kolla,Unclean,Rent,Battry,Muck,No,One_media,Own_production,No,No,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1300742,1-4,Female,Illitrate,Rural,39-60,Dega,Clean,Rent,Battry,Muck,Yes,Never,Purchase,No,Yes,No,No,Yes,No
DT0301118,1-4,Male,Illitrate,Rural,15-38,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,Yes,No,No,No,Yes,No
DT1100717,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Rent,Battry,Charcoal,Yes,One_media,Purchase,No,No,No,No,Yes,Yes
DT1200527,5-8,Male,Illitrate,Rural,61-84,Dega,Unclean,Rent,Wood/other,Muck,No,Never,Purchase,No,No,No,No,No,No
DT0300270,1-4,Male,Illitrate,Rural,61-84,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes,Yes

In [84]:
#train=x_train[train]
test=pd.concat([test,y_test],axis=1)

In [85]:
#all relevant fetures for model developmnt 
test.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'Decision'],
      dtype='object')

In [86]:
test

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,Q308m,Qsou_inform,Q504,Q5231,Q5232,Q5233,Q5234,Q524,Decision
hhid,,,,,,,,,,,,,,,,,,,
DT1201929,5-8,Male,Illitrate,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,One_media,Purchase,No,No,No,No,No,No
DT0601013,5-8,Male,Elementary,Urban,39-60,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,Yes,No,No,No,Yes,No
DT1000301,1-4,Male,Illitrate,Rural,15-38,Dega,Clean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes,No
DT0900088,1-4,Female,Elementary,Rural,39-60,Dega,Clean,Government,Electricity,Charcoal,Yes,One_media,Purchase,Yes,No,No,No,No,No
DT0700821,5-8,Male,Illitrate,Rural,39-60,Kolla,Unclean,Rent,Battry,Wood,No,Never,Own_production,No,Yes,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1201583,1-4,Male,Elementary,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,Never,Purchase,Yes,No,No,No,Yes,No
DT1100535,1-4,Male,Secondary,Urban,15-38,Dega,Clean,Rent,Electricity,Charcoal,No,Two_media,Own_production,No,No,No,No,No,Yes
DT1201563,5-8,Female,Illitrate,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,One_media,Purchase,No,No,No,No,Yes,No
DT1201095,5-8,Male,Illitrate,Rural,15-38,Dega,Unclean,Rent,Battry,Muck,No,Never,Purchase,No,No,No,No,Yes,No
DT1100908,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Private,Electricity,Electricity,No,One_media,Purchase,No,No,No,No,No,Yes

In [87]:
test.columns

Index(['hh_members', 'sex', 'hh_education', 'residence', 'age', 'altitude',
       'Q401', 'Q304', 'Q306', 'Q307', 'Q308m', 'Qsou_inform', 'Q504', 'Q5231',
       'Q5232', 'Q5233', 'Q5234', 'Q524', 'Decision'],
      dtype='object')

In [88]:
test.shape

(2726, 19)

In [89]:
config = {'algorithm': 'C4.5'}
model = chef.fit(test, config)

[INFO]:  2 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  367.71189284324646  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  93.91049156272928 % on  2726  instances
Labels:  ['No' 'Yes']
Confusion matrix:  [[1469, 52], [114, 1091]]
Precision:  96.5812 %, Recall:  92.7985 %, F1:  94.6521 %

In [90]:
if __name__ == '__main__':
    config = {'algorithm': 'C4.5', 'enableParallelism': True}
    model = chef.fit(test, config)
    fi = chef.feature_importance()
    print(fi)

[INFO]:  2 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  376.7318992614746  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  93.91049156272928 % on  2726  instances
Labels:  ['No' 'Yes']
Confusion matrix:  [[1473, 56], [110, 1087]]
Precision:  96.3375 %, Recall:  93.0512 %, F1:  94.6658 %

TypeError: feature_importance() missing 1 required positional argument: 'rules'

In [91]:
test.iloc[2001]

hh_members                 1-4
sex                       Male
hh_education         Illitrate
residence                Rural
age                      39-60
altitude            Woina_dega
Q401                   Unclean
Q304                      Rent
Q306                    Battry
Q307                      Muck
Q308m                       No
Qsou_inform              Never
Q504            Own_production
Q5231                       No
Q5232                       No
Q5233                       No
Q5234                       No
Q524                       Yes
Decision                   Yes
Name: DT0800034, dtype: object

In [92]:
test

,hh_members,sex,hh_education,residence,age,altitude,Q401,Q304,Q306,Q307,Q308m,Qsou_inform,Q504,Q5231,Q5232,Q5233,Q5234,Q524,Decision
hhid,,,,,,,,,,,,,,,,,,,
DT1201929,5-8,Male,Illitrate,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,One_media,Purchase,No,No,No,No,No,No
DT0601013,5-8,Male,Elementary,Urban,39-60,Dega,Unclean,Rent,Battry,Muck,No,Never,Own_production,Yes,No,No,No,Yes,No
DT1000301,1-4,Male,Illitrate,Rural,15-38,Dega,Clean,Rent,Battry,Muck,No,Never,Own_production,No,No,No,No,Yes,No
DT0900088,1-4,Female,Elementary,Rural,39-60,Dega,Clean,Government,Electricity,Charcoal,Yes,One_media,Purchase,Yes,No,No,No,No,No
DT0700821,5-8,Male,Illitrate,Rural,39-60,Kolla,Unclean,Rent,Battry,Wood,No,Never,Own_production,No,Yes,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DT1201583,1-4,Male,Elementary,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,Never,Purchase,Yes,No,No,No,Yes,No
DT1100535,1-4,Male,Secondary,Urban,15-38,Dega,Clean,Rent,Electricity,Charcoal,No,Two_media,Own_production,No,No,No,No,No,Yes
DT1201563,5-8,Female,Illitrate,Rural,39-60,Woina_dega,Unclean,Rent,Electricity,Charcoal,No,One_media,Purchase,No,No,No,No,Yes,No
DT1201095,5-8,Male,Illitrate,Rural,15-38,Dega,Unclean,Rent,Battry,Muck,No,Never,Purchase,No,No,No,No,Yes,No
DT1100908,1-4,Male,Teritary,Urban,15-38,Dega,Clean,Private,Electricity,Electricity,No,One_media,Purchase,No,No,No,No,No,Yes

In [93]:
test.iloc[222]

hh_members             5-8
sex                   Male
hh_education    Elementary
residence            Urban
age                  39-60
altitude              Dega
Q401                 Clean
Q304                  Rent
Q306                Battry
Q307                  Muck
Q308m                   No
Qsou_inform      One_media
Q504              Purchase
Q5231                   No
Q5232                   No
Q5233                   No
Q5234                   No
Q524                   Yes
Decision               Yes
Name: DT0600351, dtype: object

In [94]:
predction=chef.predict(model,test.iloc[222])
predction

'Yes'

In [95]:
for index,instance in test.iterrows():
    prediction=chef.predict(model,instance)
    actual=instance['Decision']
    if actual==prediction:
        classified=True
    else:
        classified=False
        print("*",end='')
   
    print(actual,"-",prediction)

No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
*No - Yes
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
*No - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*Yes - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
*Yes - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*Yes - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
*Yes - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
*Yes - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
*No - Yes
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
*No - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
*Yes - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*Yes - No
*No - Yes
No - No
No - No
*No - Yes
No - No
Yes - Yes
*No - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
*No - Yes
Yes - Yes
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*Yes - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
*No - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
*No - Yes
No - No
No - No
No - No
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
*No - Yes
Yes - Yes
Yes - Yes
*Yes - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
*No - Yes
No - No
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
*Yes - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
*Yes - No
*No - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
*No - Yes
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
*No - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
*Yes - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes

No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
No - No
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*Yes - No
Yes - Yes
*Yes - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
*Yes - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
*Yes - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
*Yes - No
*No - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
*No - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
*Yes - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
*No - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
*Yes - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
*Yes - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
*No - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
*No - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
*No - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
*Yes - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
*Yes - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*No - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*Yes - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
*Yes - No
*No - Yes
No - No
No - No
*Yes - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
*Yes - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
*Yes - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
*No - Yes
Yes - Yes
No - No
No - No
*Yes - No
*Yes - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
*No - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
*No - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
*Yes - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
*No - Yes
Yes - Yes
No - No
*Yes - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes

Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
*No - Yes
No - No
No - No
No - No
*Yes - No
Yes - Yes
No - No
*No - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
*Yes - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*Yes - No
No - No
*Yes - No
Yes - Yes
Yes - Yes
Yes - Yes
*Yes - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
*Yes - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
*No - Yes
*Yes - No
No - No
Yes - Yes
No - No
*No - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
*No - Yes
No - No
*No - Yes
No - No
*No - Yes
No - No
*No - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
*Yes - No
No - No
Yes - Yes
*Yes - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
No - No
*Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
*No - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
*No - Yes
Yes - Yes
*Yes - No
No - No
Yes - Yes
No - No
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
*No - Yes
No - No
No - No
No - No
Yes - Yes
No - No
*Yes - No
*No - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
*No - Yes
No - No
No - No
No - No
No - No
No - No
No - No
*Yes - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
*Yes - No
No - No
No - No
Yes - Yes
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
Yes - Yes
*No - Yes
No - No
Yes - Yes
No - No
No - No
Yes - Yes
*No - Yes
*No - Yes
No - No
No - No
No - No
*Yes - No
No - No
Yes - Yes
No - No
Yes - Yes
Yes - Yes
Yes - Yes
Yes - Yes
*Yes - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
Yes - Yes
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
No - No
Yes - Yes
Yes - Yes
No - No
No - No
*No - Yes
No - No
No - No
Yes - Yes
No - No
Yes - Yes
*No - Yes
No - No
Yes - Yes